services:
  alab_cabinet:
    image: alab_cabinet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/Alab_Cabinet/files:/app/files
      - ~/Alab_Cabinet/logs:/app/logs